server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/runway?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
    password:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/